DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS user_game_links CASCADE;
DROP TABLE IF EXISTS moves CASCADE;
DROP TABLE IF EXISTS game_participants CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS user_player_links CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS prep_reports CASCADE;
DROP TABLE IF EXISTS player_profiles CASCADE;
DROP TABLE IF EXISTS engine_evaluations CASCADE;
DROP TABLE IF EXISTS imports CASCADE;
DROP TABLE IF EXISTS "PlayerProfile" CASCADE;
DROP TABLE IF EXISTS "Player" CASCADE;
DROP TABLE IF EXISTS "Session" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS _prisma_migrations CASCADE;
